# This is a basic workflow to help you get started with Actions

name: Sync to Upstream

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 7 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync_with_upstream:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout HEAD
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Pull upstream changes
      id: sync
      uses: TheHorizon-Fivem/qb-truckerjob
      with:
        upstream_repository: qbcore-framework/qb-truckerjob
        upstream_branch: main
    - name: Timestamp
      run: date